# Generated by Django 5.2.7 on 2026-02-03 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio_slicer', '0006_audioslice_translation_alter_audioslice_is_idiom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(db_index=True, help_text='绝对顺序 (0, 1, 2...)')),
                ('line_type', models.CharField(choices=[('dialogue', 'Dialogue'), ('action', 'Action'), ('scene', 'Scene')], default='dialogue', max_length=20)),
                ('speaker', models.CharField(blank=True, help_text='说话人 (仅 dialogue)', max_length=100, null=True)),
                ('text', models.TextField(help_text='核心展示文本 (Clean Text，不含动作括号)')),
                ('action_note', models.TextField(blank=True, help_text='附属动作 (dialogue 中穿插的括号内容)', null=True)),
                ('raw_text', models.TextField(help_text='原始文本 (Backup)')),
                ('highlight', models.CharField(choices=[('none', 'None'), ('yellow', 'Review'), ('red', 'Hard')], default='none', help_text='复习高亮', max_length=20)),
                ('chunk', models.ForeignKey(help_text='归属的 Chunk，初始全部指向该集第一个 Chunk', on_delete=django.db.models.deletion.CASCADE, related_name='script_lines', to='audio_slicer.audiochunk')),
                ('slice', models.ForeignKey(blank=True, help_text='弱关联到具体的 AudioSlice (点击查找后绑定)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio_slicer.audioslice')),
            ],
            options={
                'ordering': ['chunk', 'index'],
                'indexes': [models.Index(fields=['chunk', 'index'], name='scripts_scr_chunk_i_2beac0_idx')],
            },
        ),
    ]
