# Generated by Django 5.2.7 on 2026-02-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptline',
            name='text_zh',
            field=models.TextField(blank=True, help_text='中文翻译', null=True),
        ),
    ]
