# Generated by Django 5.2.7 on 2026-02-11 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0008_add_cover_to_sourceaudio'),
        ('scripts', '0002_add_text_zh_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ingesting', 'Ingesting Script'), ('translating', 'Translating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('ingest_count', models.IntegerField(default=0, help_text='Number of script lines ingested')),
                ('translate_count', models.IntegerField(default=0, help_text='Number of lines translated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_tasks', to='audio_slicer.sourceaudio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
