# Generated by Django 5.2.7 on 2026-02-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0008_add_cover_to_sourceaudio'),
        ('scripts', '0003_scripttask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptline',
            options={'ordering': ['chunk', 'order']},
        ),
        migrations.RemoveIndex(
            model_name='scriptline',
            name='scripts_scr_chunk_i_2beac0_idx',
        ),
        migrations.AddField(
            model_name='scriptline',
            name='order',
            field=models.FloatField(db_index=True, help_text='排序权重，支持小数插入 (1.5 = 在1和2之间)', null=True),
        ),
        migrations.AlterField(
            model_name='scriptline',
            name='index',
            field=models.IntegerField(db_index=True, help_text='原始导入顺序 (0, 1, 2...), 不可修改'),
        ),
        migrations.AddIndex(
            model_name='scriptline',
            index=models.Index(fields=['chunk', 'order'], name='scripts_scr_chunk_i_61da13_idx'),
        ),
    ]
