# Generated by Django 5.2.7 on 2026-02-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_populate_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptline',
            name='order',
            field=models.FloatField(db_index=True, default=0, help_text='排序权重，支持小数插入 (1.5 = 在1和2之间)'),
        ),
    ]
