# Generated by Django 5.2.7 on 2026-02-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_make_order_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptline',
            name='order',
            field=models.FloatField(default=0, help_text='排序权重，支持小数插入 (1.5 = 在1和2之间)'),
        ),
    ]
