# Generated by Django 5.2.7 on 2026-02-25 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Original URL of the article', max_length=1024)),
                ('title', models.CharField(blank=True, help_text='Extracted title', max_length=500)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_html', models.TextField(blank=True, help_text='Cleaned HTML from Readability.js')),
                ('raw_text', models.TextField(blank=True, help_text='Plain text from Readability.js')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('meta_context', models.JSONField(blank=True, default=dict, help_text='Silently populated by LLM. Stores logic skeleton (outline) and domain attributes (domain, tone)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(db_index=True, help_text='Sequential index of the paragraph (0, 1, 2...)')),
                ('content', models.TextField(help_text='The text of the paragraph')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='reader.article')),
            ],
            options={
                'ordering': ['article', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField(help_text='The text selected by the user')),
                ('user_note', models.TextField(blank=True, help_text="User's reflections/notes")),
                ('annotation_type', models.CharField(choices=[('yellow', 'Jargon (Yellow)'), ('blue', 'Usage (Blue)'), ('pink', 'Thought (Pink)')], default='yellow', help_text='Type of annotation which dictates the AI Copilot persona', max_length=20)),
                ('ai_response', models.JSONField(blank=True, help_text='Dynamic AI response based on annotation type', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='reader.paragraph')),
            ],
        ),
        migrations.AddIndex(
            model_name='paragraph',
            index=models.Index(fields=['article', 'index'], name='reader_para_article_2bb7ad_idx'),
        ),
    ]
