# Generated by Django 5.2.7 on 2026-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='translation',
            field=models.TextField(blank=True, help_text='The Chinese translated text of the paragraph'),
        ),
    ]
