# Generated by Django 5.2.7 on 2026-02-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_paragraph_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('translating', 'Translating'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
    ]
