# Generated by Django 5.2.7 on 2026-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(help_text='Original URL of the article', max_length=1024),
        ),
    ]
