# Generated by Django 5.2.7 on 2025-11-11 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A tag for an audio slice, e.g., 'Flap T', 'H-Deletion'", max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Friends, The Office', max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(help_text='Season number, e.g., 10')),
                ('episode', models.PositiveIntegerField(help_text='Episode number, e.g., 12')),
                ('title', models.CharField(blank=True, help_text="Optional title for the audio source, e.g., 'The Last One'", max_length=255)),
                ('file', models.FileField(upload_to='audio_slicer/originals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audio_slicer.drama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('drama', 'season', 'episode')},
            },
        ),
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(help_text='Index of the chunk within the source audio (e.g., 0, 1, 2...)')),
                ('file', models.FileField(upload_to='audio_slicer/chunks/')),
                ('has_slices', models.BooleanField(default=False, help_text='Indicates if this chunk has any AudioSlices associated with it')),
                ('source_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_slicer.sourceaudio')),
            ],
            options={
                'unique_together': {('source_audio', 'chunk_index')},
            },
        ),
        migrations.CreateModel(
            name='AudioSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(help_text='Start time of the slice in seconds')),
                ('end_time', models.FloatField(help_text='End time of the slice in seconds')),
                ('file', models.FileField(upload_to='audio_slicer/slices/')),
                ('original_text', models.TextField(blank=True, help_text='Original text content of the audio slice')),
                ('notes', models.TextField(blank=True, help_text="User's personal notes for this slice")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_slicer.audiochunk')),
                ('tags', models.ManyToManyField(blank=True, to='audio_slicer.audiotag')),
            ],
            options={
                'unique_together': {('audio_chunk', 'start_time', 'end_time')},
            },
        ),
    ]
