# Generated by Django 5.2.7 on 2026-01-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioslice',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark slice as favorite for review'),
        ),
    ]
