# Generated by Django 5.2.7 on 2025-11-12 11:31

import audio_slicer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiochunk',
            name='file',
            field=models.FileField(upload_to=audio_slicer.models.audio_chunk_upload_path),
        ),
        migrations.AlterField(
            model_name='audioslice',
            name='file',
            field=models.FileField(upload_to=audio_slicer.models.audio_slice_upload_path),
        ),
    ]
