# Generated by Django 5.2.7 on 2026-01-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0002_audioslice_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioslice',
            name='favorite_category',
            field=models.CharField(blank=True, help_text="Category of favorite:'pronunciation', 'idiom'", max_length=50, null=True),
        ),
    ]
