# Generated by Django 5.2.7 on 2026-01-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0003_add_favorite_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioslice',
            name='is_idiom',
            field=models.BooleanField(default=False, help_text='Mark slice as containing idioms'),
        ),
        migrations.AddField(
            model_name='audioslice',
            name='is_pronunciation_hard',
            field=models.BooleanField(default=False, help_text='Mark slice as hard for pronunciation'),
        ),
    ]
