# Generated by Django 5.2.7 on 2026-01-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0004_add_pronunciation_and_idiom_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioslice',
            name='favorite_category',
        ),
        migrations.RemoveField(
            model_name='audioslice',
            name='is_favorite',
        ),
    ]
