# Generated by Django 5.2.7 on 2026-01-25 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0005_remove_audioslice_favorite_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audioslice',
            name='translation',
            field=models.TextField(blank=True, help_text='Chinese translation for SRS review', null=True),
        ),
        migrations.AlterField(
            model_name='audioslice',
            name='is_idiom',
            field=models.BooleanField(default=False, help_text='Mark slice as containing idioms (Auto-triggers ReviewCard creation)'),
        ),
        migrations.CreateModel(
            name='ReviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_level', models.PositiveIntegerField(default=1, help_text='Leitner box level (1-5)')),
                ('next_review_date', models.DateField(help_text='When this card is due for review')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_type', models.CharField(choices=[('translation', 'Translation (CN -> EN)'), ('listening', 'Listening (Audio -> EN)')], default='translation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_slice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_card', to='audio_slicer.audioslice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
