# Generated by Django 5.2.7 on 2026-02-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0006_audioslice_translation_alter_audioslice_is_idiom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiochunk',
            options={'ordering': ['source_audio', 'chunk_index']},
        ),
        migrations.AddField(
            model_name='audiochunk',
            name='is_studied',
            field=models.BooleanField(db_index=True, default=False, help_text='已完成复习'),
        ),
        migrations.AddField(
            model_name='audiochunk',
            name='last_studied_at',
            field=models.DateTimeField(blank=True, help_text='最后复习时间', null=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='剧集封面/海报', null=True, upload_to='covers/%Y/%m/'),
        ),
    ]
