# Generated by Django 5.2.7 on 2026-02-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0007_add_dashboard_fields_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceaudio',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Episode cover/screenshot for plot recall', null=True, upload_to='covers/episodes/%Y/%m/'),
        ),
    ]
