# Generated by Django 5.2.7 on 2026-03-04 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0008_add_cover_to_sourceaudio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceaudio',
            options={'ordering': ['drama', 'season', 'episode']},
        ),
        migrations.AlterUniqueTogether(
            name='sourceaudio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='drama',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sourceaudio',
            name='drama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audios', to='audio_slicer.drama'),
        ),
        migrations.AlterField(
            model_name='sourceaudio',
            name='title',
            field=models.CharField(blank=True, default='', help_text="Optional title for the audio source, e.g., 'The Last One'", max_length=255),
        ),
        migrations.AlterField(
            model_name='sourceaudio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sourceaudio',
            constraint=models.UniqueConstraint(fields=('drama', 'season', 'episode'), name='unique_episode'),
        ),
    ]
