# Generated by Django 5.2.7 on 2026-03-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0009_alter_sourceaudio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiochunk',
            name='source_audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='audio_slicer.sourceaudio'),
        ),
    ]
