# Generated by Django 5.2.7 on 2026-03-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0010_alter_audiochunk_source_audio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audiochunk',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='audioslice',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='audiochunk',
            constraint=models.UniqueConstraint(fields=('source_audio', 'chunk_index'), name='unique_chunk_within_audio'),
        ),
        migrations.AddConstraint(
            model_name='audioslice',
            constraint=models.UniqueConstraint(fields=('audio_chunk', 'start_time', 'end_time'), name='unique_slice_times'),
        ),
    ]
