# Generated by Django 5.2.7 on 2026-03-04 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0011_alter_audiochunk_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioslice',
            name='audio_chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='audio_slicer.audiochunk'),
        ),
    ]
