# Generated by Django 5.2.7 on 2026-03-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_slicer', '0012_alter_audioslice_audio_chunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcard',
            name='box_level',
            field=models.PositiveIntegerField(choices=[(1, 'Box 1 (Daily)'), (2, 'Box 2 (Every 3 Days)'), (3, 'Box 3 (Weekly)'), (4, 'Box 4 (Bi-weekly)'), (5, 'Box 5 (Mastered)')], default=1, help_text='Leitner box level (1-5)'),
        ),
    ]
