"""
Django settings for sample_project project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# DITA path configuration
PROJECT_BASE_DIR = BASE_DIR.parent
DITA_DOCS_DIR = PROJECT_BASE_DIR / 'docs' / 'dita'


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

raw_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1')
ALLOWED_HOSTS = raw_hosts.split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 3rd Party: DRF & Authentication
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django.contrib.sites', 
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'corsheaders',
    'huey.contrib.djhuey',
    
    # Local Apps
    'phrase_log',
    'audio_slicer',
    'ai_analysis',
    'doc_assistant',
    'sandbox',
    'scripts',
    'reader',
    'pomodoro',
    'english_corner',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Configure Authentication Backends (allauth for email login)
AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Required by dj-rest-auth for site tracking
SITE_ID = 1

ROOT_URLCONF = 'sample_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sample_project.wsgi.application'


# Database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication', # For Chrome Extension
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 15,
}

# Simple JWT Configuration
if DEBUG: 
    SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
        "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    }

# dj-rest-auth Configuration
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'my-auth-cookie',
    'JWT_AUTH_REFRESH_COOKIE': 'my-refresh-cookie',
}

# Allauth Configuration
ACCOUNT_AUTHENTICATION_METHODS = ['email']
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_NORMALIZATION = True # Ensure emails are stored in lowercase
ACCOUNT_CONFIRM_EMAIL_ON_GET = True # Auto-confirm email on GET request to confirmation link

ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = 'http://localhost:5173/login'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = 'http://localhost:5173/'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static & Media Files
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS ALLOWED ORIGINS
raw_cors = os.environ.get('DJANGO_CORS_ORIGINS', 'http://localhost:5173')
CORS_ALLOWED_ORIGINS = raw_cors.split(',')

# 允许跨域的 CSRF 来源（比如 Vite 开发服务器）
CSRF_TRUSTED_ORIGINS = raw_cors.split(',')

# 允许前端发送 Cookie（比如登录的 Session 或 JWT 令牌）
CORS_ALLOW_CREDENTIALS = True

# Development Email Configuration: Prints emails to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Huey Task Queue Configuration
from huey import SqliteHuey
HUEY = SqliteHuey(
    filename=str(BASE_DIR / 'db' / 'huey.db'),
    immediate_use_memory=False,
)

# LLM Configuration
# Per-feature model selection. 
# If a feature is not explicitly configured, it falls back to 'default'.
LLM_CONFIG = {
    "default": {
        "provider": "deepseek",
        "model_name": "deepseek-chat",
        "temperature": 0.3,
        "api_key": os.getenv("DEEPSEEK_API_KEY"),
        "base_url": os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com"),
    },
    "sound_script": {
        "provider": "gemini",
        "model_name": os.getenv("MODEL_NAME", "gemini-2.5-flash"),
        "temperature": 0,
        "api_key": os.getenv("GOOGLE_API_KEY"),
    },
    "article_meta": {
        "provider": "gemini",
        "model_name": os.getenv("MODEL_NAME", "gemini-2.5-flash"),
        "temperature": 0,
        "api_key": os.getenv("GOOGLE_API_KEY"),
    },
    # "reader_copilot": {
    #     "provider": "gemini",
    #     "model_name": os.getenv("MODEL_NAME", "gemini-2.5-flash"),
    #     "temperature": 0,
    #     "api_key": os.getenv("GOOGLE_API_KEY"),
    # },
    "english_corner": {
        "provider": "deepseek",
        "model_name": "deepseek-chat",
        "temperature": 0.7,
        "api_key": os.getenv("DEEPSEEK_API_KEY"),
        "base_url": os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com"),
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        # 1. 打印到终端
        'console': {
            'class': 'logging.StreamHandler',
        },
        # 2. 写入到文件
        'file': {
            'level': 'INFO', # 记录 INFO 及以上级别的日志
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'django_debug.log'), # 保存在后端根目录
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'loggers': {
        # 我们这里的意思是：拦截所有来自 reader app 的日志
        'reader': {
            'handlers': ['console', 'file'], # 同时打在屏幕上和写入文件里
            'level': 'INFO',
            'propagate': True,
        },
    },
}
# Huey Background Tasks Configuration
import os
HUEY = {
    'huey_class': 'huey.SqliteHuey',  # Use SQLite for queue (no Redis needed)
    'name': 'lingua_huey',
    'results': True,  # Store return values of tasks
    'store_none': False,
    'immediate': True,  # True means run tasks synchronously (in-band)
    'connection': {
        'filename': os.path.join(BASE_DIR, 'huey.sqlite3'),
    },
}
