# Generated by Django 5.2.7 on 2026-03-12 11:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phrase_log', '0006_delete_sourceaudio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='Rolling summary generated by LLM')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('user_content', models.TextField(blank=True, default='')),
                ('tutor_polished_text', models.TextField(blank=True, default='')),
                ('tutor_explanation_cn', models.TextField(blank=True, default='')),
                ('character_content', models.TextField(blank=True, default='')),
                ('audio_url', models.CharField(blank=True, default='', help_text='Relative URL to generated TTS WAV file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='english_corner.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_phrase', models.CharField(max_length=300)),
                ('prompt_question', models.TextField(help_text="The 'Q' prompt for review")),
                ('answer', models.TextField(help_text='Expected answer')),
                ('example_context', models.TextField(blank=True, default='')),
                ('box_level', models.PositiveIntegerField(default=1, help_text='Leitner box 1-5')),
                ('next_review_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, help_text='The message this flashcard was extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='english_corner.practicemessage')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='☕', max_length=50)),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Auto-generated from title + description if left blank')),
                ('is_preset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for global/preset scenarios', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_corner.scenario'),
        ),
        migrations.CreateModel(
            name='WordNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('node_type', models.CharField(choices=[('keyword', 'Keyword'), ('phrase', 'Phrase')], default='keyword', max_length=20)),
                ('explanation', models.TextField(blank=True, default='')),
                ('example', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='LLM enrichment status', max_length=20)),
                ('mastery', models.PositiveIntegerField(default=0, help_text='0-100 percentage')),
                ('box_level', models.PositiveIntegerField(default=1, help_text='SRS box level (1-5)')),
                ('embedding', models.JSONField(blank=True, help_text='1536-dim vector for semantic search/linking', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phrase_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_node', to='phrase_log.phraselog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(help_text="e.g., 'scenario' or 'vocab'", max_length=20)),
                ('source_id', models.CharField(max_length=50)),
                ('target_type', models.CharField(help_text="e.g., 'vocab'", max_length=20)),
                ('target_id', models.CharField(max_length=50)),
                ('relation', models.CharField(default='context', help_text="e.g., 'context', 'synonym', 'contrast'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'source_type', 'source_id', 'target_type', 'target_id', 'relation')},
            },
        ),
    ]
