# Generated by Django 5.2.7 on 2026-03-27 07:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_corner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wordnode',
            name='next_review_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='SRS next review timestamp'),
        ),
        migrations.AddField(
            model_name='wordnode',
            name='scenarios',
            field=models.JSONField(blank=True, default=list, help_text="LLM-generated scenarios: [{'description': '...', 'tag': 'Office'}, ...]"),
        ),
        migrations.CreateModel(
            name='DailyPracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('words_practiced', models.IntegerField(default=0)),
                ('word_ids', models.JSONField(default=list, help_text='3 WordNode IDs for today: [12, 45, 89]')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_log')],
            },
        ),
    ]
