# Generated by Django 5.2.7 on 2026-04-08 06:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_corner', '0002_wordnode_next_review_at_wordnode_scenarios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordLink',
            new_name='LegacyWordLink',
        ),
    ]
