# Generated by Django 5.2.7 on 2026-04-08 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('english_corner', '0003_rename_wordlink_legacywordlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_sentence', models.TextField(help_text='划词时所在的具体上下文句子')),
                ('object_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='english_corner.wordnode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('variant', '变形/派生'), ('synonym', '同义/近义表达'), ('antonym', '反义表达')], default='synonym', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='english_corner.wordnode')),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='english_corner.wordnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'english_corner_wordlink_v2',
                'unique_together': {('user', 'source_word', 'target_word', 'relation')},
            },
        ),
    ]
