# Generated by Django 5.2.7 on 2026-04-08 08:01

from django.db import migrations
import re

def migrate_legacy_links(apps, schema_editor):
    LegacyWordLink = apps.get_model('english_corner', 'LegacyWordLink')
    WordOccurrence = apps.get_model('english_corner', 'WordOccurrence')
    WordLink = apps.get_model('english_corner', 'WordLink')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    WordNode = apps.get_model('english_corner', 'WordNode')
    PracticeMessage = apps.get_model('english_corner', 'PracticeMessage')
    Scenario = apps.get_model('english_corner', 'Scenario')

    for link in LegacyWordLink.objects.all():
        if link.target_type == 'vocab':
            try:
                target_word = WordNode.objects.get(id=int(link.target_id))
            except (WordNode.DoesNotExist, ValueError):
                continue

            if link.source_type == 'message':
                try:
                    message_obj = PracticeMessage.objects.get(id=int(link.source_id))
                    content_type, _ = ContentType.objects.get_or_create(app_label='english_corner', model='practicemessage')
                    
                    full_text = message_obj.character_content or message_obj.user_content or ""
                    exact_sentence = ""
                    if full_text:
                        # Split by generic sentence boundaries
                        sentences = re.split(r'(?<=[.!?])\s+', full_text.strip())
                        target_phrase = target_word.label.lower()
                        for sentence in sentences:
                            if target_phrase in sentence.lower():
                                exact_sentence = sentence.strip()
                                break
                        
                        if not exact_sentence:
                            exact_sentence = full_text.strip()
                            
                    WordOccurrence.objects.get_or_create(
                        user=link.user,
                        word=target_word,
                        content_type=content_type,
                        object_id=str(message_obj.id),
                        defaults={'exact_sentence': exact_sentence}
                    )
                except (PracticeMessage.DoesNotExist, ValueError):
                    pass
            elif link.source_type == 'scenario':
                try:
                    scenario_obj = Scenario.objects.get(id=int(link.source_id))
                    content_type, _ = ContentType.objects.get_or_create(app_label='english_corner', model='scenario')
                    
                    exact_sentence = scenario_obj.description or scenario_obj.title or ""
                    WordOccurrence.objects.get_or_create(
                        user=link.user,
                        word=target_word,
                        content_type=content_type,
                        object_id=str(scenario_obj.id),
                        defaults={'exact_sentence': exact_sentence}
                    )
                except (Scenario.DoesNotExist, ValueError):
                    pass
            elif link.source_type == 'vocab':
                try:
                    source_word = WordNode.objects.get(id=int(link.source_id))
                    WordLink.objects.get_or_create(
                        user=link.user,
                        source_word=source_word,
                        target_word=target_word,
                        relation=link.relation
                    )
                except (WordNode.DoesNotExist, ValueError):
                    pass

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('english_corner', '0004_wordoccurrence_wordlink'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_links, reverse_migration),
    ]
