# Generated by Django 5.2.7 on 2026-04-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_corner', '0005_migrate_legacy_wordlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacyWordLink',
        ),
    ]
