# Generated by Django 5.2.7 on 2026-04-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_corner', '0006_delete_legacywordlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordnode',
            name='tag',
            field=models.CharField(choices=[('explainer', '解说员/串联词'), ('industry', '行业/职场'), ('casual', '生活通用'), ('vibe', '网络社区/慎用'), ('literary', '文学/低频'), ('misc', '杂项/待定')], default='misc', help_text='Custom tagging for filtering/practice priority', max_length=20),
        ),
    ]
