# Generated by Django 5.2.7 on 2025-10-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_context', models.CharField(max_length=500)),
                ('expression_text', models.CharField(max_length=500)),
                ('chinese_meaning', models.CharField(max_length=500)),
                ('example_sentence', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
