# Generated by Django 5.2.7 on 2025-11-03 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Tech English', 'Daily Life'", max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhraseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_context', models.CharField(max_length=500)),
                ('expression_text', models.CharField(max_length=500)),
                ('chinese_meaning', models.CharField(max_length=500)),
                ('example_sentence', models.CharField(max_length=500)),
                ('tested', models.PositiveIntegerField(default=0, help_text='Count of times this was included in a quiz')),
                ('failed', models.PositiveIntegerField(default=0, help_text='Count of times this was failed in a quiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='phrase_log.tag')),
            ],
        ),
    ]
