# Generated by Django 5.2.7 on 2025-11-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phraselog',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
