# Generated by Django 5.2.7 on 2025-11-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_log', '0002_phraselog_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='phraselog',
            name='failed_radio',
            field=models.FloatField(default=0, help_text='Ratio of failure to total quizzes'),
        ),
    ]
