# Generated by Django 5.2.7 on 2025-11-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_log', '0003_phraselog_failed_radio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phraselog',
            name='failed_radio',
            field=models.PositiveIntegerField(default=100, help_text='Ratio of failure. Defaults to 100 for untested items.'),
        ),
    ]
