# Generated by Django 5.2.7 on 2025-11-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_log', '0004_alter_phraselog_failed_radio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='originals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
