# Generated by Django 5.2.7 on 2025-11-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phrase_log', '0005_sourceaudio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceAudio',
        ),
    ]
