# Generated by Django 6.0.2 on 2026-02-27 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='用于在 UI 矩阵中排序')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='按下开始键的瞬间')),
                ('completed_at', models.DateTimeField(auto_now_add=True, help_text='专注倒计时自然结束的瞬间')),
                ('duration', models.IntegerField(help_text='设定的专注时长 (分钟)')),
                ('task', models.CharField(blank=True, help_text='预留字段，日后手动补全专注细节', max_length=500, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('interrupted', 'Interrupted')], default='completed', max_length=20)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pomodoros', to='pomodoro.pomodorotag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
