# Generated by Django 6.0.2 on 2026-02-27 07:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pomodoros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='专注真正结束的瞬间', null=True),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='duration',
            field=models.IntegerField(help_text='设定的专注时长 (分钟)', validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('interrupted', 'Interrupted')], default='started', max_length=20),
        ),
    ]
