# Generated by Django 6.0.2 on 2026-02-27 07:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPomodoroTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名称，例如：沉浸美剧', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='用于在前端 Tag 矩阵中排序')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PPomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='专注倒计时自然结束的瞬间', null=True)),
                ('duration', models.IntegerField(help_text='专注时长 (分钟)', validators=[django.core.validators.MinValueValidator(5)])),
                ('task', models.CharField(blank=True, help_text='预留字段，日后手动补全专注细节', max_length=200, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('interrupted', 'Interrupted')], default='interrupted', help_text='专注状态')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ppomodoros', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppomodoros', to='sandbox.ppomodorotag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
