# Generated by Django 6.0.2 on 2026-02-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0003_alter_ppomodoro_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppomodoro',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='ppomodoro',
            name='user',
        ),
        migrations.DeleteModel(
            name='PPomodoroTag',
        ),
        migrations.DeleteModel(
            name='PPomodoro',
        ),
    ]
