# Generated by Django 5.2.7 on 2026-02-28 04:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0004_remove_ppomodoro_tag_remove_ppomodoro_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTagSandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='用于在 UI 矩阵中排序')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PSandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='按下开始键的瞬间')),
                ('completed_at', models.DateTimeField(blank=True, help_text='专注真正结束的瞬间', null=True)),
                ('duration', models.IntegerField(help_text='设定的专注时长 (分钟)', validators=[django.core.validators.MinValueValidator(5)])),
                ('task', models.CharField(blank=True, help_text='预留字段，日后手动补全专注细节', max_length=500, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('interrupted', 'Interrupted')], default='started', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psandboxes', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='psandboxes', to='sandbox.ptagsandbox')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
