# Generated by Django 5.2.7 on 2026-04-08 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0005_ptagsandbox_psandbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the Article', max_length=500)),
                ('url', models.URLField(help_text='URL of the article', max_length=1024)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('translating', 'Translating'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last Updated Time')),
                ('raw_text', models.TextField(blank=True, help_text='Raw text extracted from Readability.js')),
                ('raw_html', models.TextField(blank=True, help_text='Raw html extracted from Readability.js')),
                ('ai_context', models.JSONField(blank=True, default=dict, help_text='Article Meta Data from LLM')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarticles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='Sequential index of the paragraph (0-based)')),
                ('content', models.TextField(help_text='The text of the paragraph')),
                ('translation', models.TextField(blank=True, help_text='The Chinese translated text of the paragraph')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sparagraphs', to='sandbox.sarticle')),
            ],
            options={
                'ordering': ['article', 'index'],
            },
        ),
        migrations.CreateModel(
            name='SAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField(help_text='Text to explain')),
                ('user_note', models.CharField(blank=True, help_text="User's comment", max_length=200)),
                ('annotation_type', models.CharField(choices=[('blue', 'Usage (Blue)'), ('pink', 'Thought (Pink)'), ('yellow', 'Jargon (Yellow)')], default='yellow', max_length=20)),
                ('ai_response', models.JSONField(blank=True, default=dict, help_text='Dynamic AI response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sannotations', to='sandbox.sparagraph')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sparagraph',
            index=models.Index(fields=['article', 'index'], name='sandbox_spa_article_f93ca0_idx'),
        ),
    ]
